# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(245, 250, 254);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.header_widget = QtWidgets.QWidget(self.widget_3)
        self.header_widget.setObjectName("header_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.header_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menubtn = QtWidgets.QPushButton(self.header_widget)
        self.menubtn.setStyleSheet("border:none;\n"
"border-image: url(:/newPrefix/menu.png);\n"
"")
        self.menubtn.setText("")
        self.menubtn.setCheckable(True)
        self.menubtn.setAutoExclusive(True)
        self.menubtn.setObjectName("menubtn")
        self.horizontalLayout.addWidget(self.menubtn)
        spacerItem = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.header_widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.findbtn = QtWidgets.QPushButton(self.header_widget)
        self.findbtn.setStyleSheet("border-image: url(:/newPrefix/search-interface-symbol.png);")
        self.findbtn.setText("")
        self.findbtn.setObjectName("findbtn")
        self.horizontalLayout.addWidget(self.findbtn)
        spacerItem1 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.header_widget)
        self.stackedWidget_2.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.donhang = QtWidgets.QWidget()
        self.donhang.setObjectName("donhang")
        self.label = QtWidgets.QLabel(self.donhang)
        self.label.setGeometry(QtCore.QRect(210, 230, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stackedWidget_2.addWidget(self.donhang)
        self.lotrinh = QtWidgets.QWidget()
        self.lotrinh.setObjectName("lotrinh")
        self.label_2 = QtWidgets.QLabel(self.lotrinh)
        self.label_2.setGeometry(QtCore.QRect(230, 180, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget_2.addWidget(self.lotrinh)
        self.thongbao = QtWidgets.QWidget()
        self.thongbao.setObjectName("thongbao")
        self.stackedWidget_2.addWidget(self.thongbao)
        self.caidat = QtWidgets.QWidget()
        self.caidat.setObjectName("caidat")
        self.stackedWidget_2.addWidget(self.caidat)
        self.gridLayout_2.addWidget(self.stackedWidget_2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.header_widget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_3, 0, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("QWidget{background-color: rgb(85, 170, 255)}\n"
"QPushButton{\n"
"    color: white;\n"
"    text-align:left;\n"
"height: 40px;\n"
"border:none;\n"
"padding-left:10px;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:checked{\n"
"background-color: #f5fafe;\n"
"color: #f195ef;\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.userlb = QtWidgets.QLabel(self.widget_2)
        self.userlb.setMinimumSize(QtCore.QSize(40, 40))
        self.userlb.setMaximumSize(QtCore.QSize(40, 40))
        self.userlb.setStyleSheet("border-image: url(:/newPrefix/user.png);")
        self.userlb.setText("")
        self.userlb.setScaledContents(True)
        self.userlb.setObjectName("userlb")
        self.horizontalLayout_3.addWidget(self.userlb)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 12, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.donhangbtn = QtWidgets.QPushButton(self.widget_2)
        self.donhangbtn.setMinimumSize(QtCore.QSize(0, 10))
        self.donhangbtn.setCheckable(True)
        self.donhangbtn.setAutoExclusive(True)
        self.donhangbtn.setObjectName("donhangbtn")
        self.verticalLayout_2.addWidget(self.donhangbtn)
        self.lotrinhbtn = QtWidgets.QPushButton(self.widget_2)
        self.lotrinhbtn.setCheckable(True)
        self.lotrinhbtn.setAutoExclusive(True)
        self.lotrinhbtn.setObjectName("lotrinhbtn")
        self.verticalLayout_2.addWidget(self.lotrinhbtn)
        self.thongbaobtn = QtWidgets.QPushButton(self.widget_2)
        self.thongbaobtn.setCheckable(True)
        self.thongbaobtn.setAutoExclusive(True)
        self.thongbaobtn.setObjectName("thongbaobtn")
        self.verticalLayout_2.addWidget(self.thongbaobtn)
        self.caidatbtn = QtWidgets.QPushButton(self.widget_2)
        self.caidatbtn.setCheckable(True)
        self.caidatbtn.setAutoExclusive(True)
        self.caidatbtn.setObjectName("caidatbtn")
        self.verticalLayout_2.addWidget(self.caidatbtn)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 250, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.dangxuatbtn1 = QtWidgets.QPushButton(self.widget_2)
        self.dangxuatbtn1.setCheckable(True)
        self.dangxuatbtn1.setAutoExclusive(True)
        self.dangxuatbtn1.setObjectName("dangxuatbtn1")
        self.verticalLayout_4.addWidget(self.dangxuatbtn1)
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        self.menubtn.toggled['bool'].connect(self.widget_2.setVisible) # type: ignore
        self.dangxuatbtn1.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.dangxuatbtn1.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Trang đơn hàng"))
        self.label_2.setText(_translate("MainWindow", "Trang lộ trình"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.donhangbtn.setText(_translate("MainWindow", "Đơn hàng"))
        self.lotrinhbtn.setText(_translate("MainWindow", "Lộ trình"))
        self.thongbaobtn.setText(_translate("MainWindow", "Thông báo"))
        self.caidatbtn.setText(_translate("MainWindow", "Cài đặt"))
        self.dangxuatbtn1.setText(_translate("MainWindow", "Đăng xuất"))
# import resources_rc

